apiVersion: apps/v1

kind: Deployment

metadata:

  name: go-maths-app

  labels:

    app: web

spec:

  replicas: 2

  selector:

    matchLabels:

      app: web

  template:

    metadata:

      labels:

        app: web

    spec:

      containers:

        - name: go-maths-app

          image: jonathanmarriott/go-maths-app

          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
