name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        cd src
        go build -v ./...

    - name: Test
      run: |
        cd src
        go test -v ./...
        
  build-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PW }}" | docker login  --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build . --file Dockerfile.production --tag ${{ secrets.DOCKER_USERNAME }}/go-maths-app:$(date +%s)
        docker push ${{ secrets.DOCKER_USERNAME }}/go-maths-app
